######################################
# str: message sent to uC
# size: how big (in bytes) of a return message 
#       you expect
# time: how long (in msec) the node should 
#       wait before looking for a response from uC
# -----------
# str: returned message from uC
# NOTE: string already holds size and time wasn't
#       useful in practice
######################################
string str 
#uint8 size
#uint16 time
--------
string str